version: '3.7'

services:

  device:
    build:
      context: ./src
      dockerfile: Dockerfile-device
    volumes:
      - "./src:/app"
    environment:
      - NAME_SERVER_IP=172.28.0.2
      - NAME_SERVER_PORT=9090
      - GATEWAY_NAME=gateway01
    container_name: device01
    networks:
      backend:
        ipv4_address: 172.28.0.4
    links:
      - name-server
      - gateway
    depends_on:
      - gateway

  gateway:
    build:
      context: ./src
      dockerfile: Dockerfile-gateway
    volumes:
      - "./src:/app"
    environment:
      - NAME_SERVER_IP=172.28.0.2
      - NAME_SERVER_PORT=9090
      - GATEWAY_NAME=gateway01
    container_name: gateway01
    networks:
      backend:
        ipv4_address: 172.28.0.3
    ports:
      - "9999:9999"
    links:
      - name-server
    depends_on:
      - name-server

  name-server:
    build: ./name-server
    container_name: name-server
    networks:
      backend:
        ipv4_address: 172.28.0.2
    ports:
      - "9090:9090"

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
